# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myitems.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'myitems.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyitems.proto\x12\x07myitems\"\x19\n\x0bItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"&\n\nSendStream\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"(\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\'\n\x10ItemsAddedResult\x12\x13\n\x0btotal_count\x18\x01 \x01(\x05\",\n\x0b\x43hatMessage\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\x82\x02\n\x0bItemService\x12:\n\x0bGetItemById\x12\x14.myitems.ItemRequest\x1a\x15.myitems.ItemResponse\x12\x37\n\x0cListAllItems\x12\x0e.myitems.Empty\x1a\x15.myitems.ItemResponse0\x01\x12<\n\x08\x41\x64\x64Items\x12\x13.myitems.SendStream\x1a\x19.myitems.ItemsAddedResult(\x01\x12@\n\x0e\x43hatAboutItems\x12\x14.myitems.ChatMessage\x1a\x14.myitems.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myitems_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMREQUEST']._serialized_start=26
  _globals['_ITEMREQUEST']._serialized_end=51
  _globals['_SENDSTREAM']._serialized_start=53
  _globals['_SENDSTREAM']._serialized_end=91
  _globals['_ITEMRESPONSE']._serialized_start=93
  _globals['_ITEMRESPONSE']._serialized_end=133
  _globals['_ITEMSADDEDRESULT']._serialized_start=135
  _globals['_ITEMSADDEDRESULT']._serialized_end=174
  _globals['_CHATMESSAGE']._serialized_start=176
  _globals['_CHATMESSAGE']._serialized_end=220
  _globals['_EMPTY']._serialized_start=222
  _globals['_EMPTY']._serialized_end=229
  _globals['_ITEMSERVICE']._serialized_start=232
  _globals['_ITEMSERVICE']._serialized_end=490
# @@protoc_insertion_point(module_scope)
